### ISSUE TITLE
what's VisualReview?

### ISSUE THREAD

**Issue by dylang** [xebia/VisualReview-protractor#1]
This sounds like something my team might be interested in, but we're not sure what VisualReview is. An open source project? A paid service? 

Thanks!

**Comment by skwakman** [comment]
Damn that was quick :). To quote its github page, VisualReview strives to provide a productive and human-friendly workflow for testing and reviewing a web application's layout across several browsers, resolutions and platforms. More details here: https://github.com/xebia/VisualReview

Note that we pushed the first bits of code and a very early preview-release _a few hours ago_. There's still loads to be done for a stable 1.0, however early feedback is welcome.
